export const FETCH_LESSON = "FETCH_LESSON";
export const FETCH_SINGLE_LESSON = "FETCH_SINGLE_LESSON";
export const CREATE_LESSON = "CREATE_LESSON";
export const UPDATE_LESSON = "UPDATE_LESSON";
export const DELETE_LESSON = "DELETE_LESSON";

